site_name: FedPredict
site_url: https://www.fedpredict.com/
nav:
  - Home: index.md
  - Examples:
      - 'Quick start': quick_start.md
      - 'Flower + FedPredict': flower_fedpredict.md
  - Projects: projects.md
  - API Reference:
      - 'Pytorch': api_reference_torch.md
  - About: about.md
